### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by devsecfranklin** [devsecfranklin/pso-gcp-keybank-542851#130]
```


Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, 
in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952,
 in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821,
 in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39,
 in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950,
 in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, 
in view_func function(data, context) File "/workspace/main.py", line 204, 
in main tags_list = dedupe_tags(vm_data) File "/workspace/main.py",
 line 96, in dedupe_tags for tag in object["Tags"]: TypeError: list indices must be integers or slices, not str

```

**Comment by devsecfranklin** [comment]
Pull tags from this list:
```
 INFO:root:Checking object [{'Name': 'instance-1', 'Tags': ['https-server', '1092034061644-compute@developer.gserviceaccount.com'], 'IP': '10.128.0.2', 'ServiceAccount': '1092034061644-compute@developer.gserviceaccount.com', 'UnifiedTags': None}]
```

**Comment by devsecfranklin** [comment]
fixed
```
Default

2021-09-14T17:54:32.979Z

keybank_gcp_taggingicursunhu9ry INFO:root:Found a tag esa-it-abinitio

Default

2021-09-14T17:54:32.979Z

keybank_gcp_taggingicursunhu9ry INFO:root:Found a tag it

Default

2021-09-14T17:54:32.979Z

keybank_gcp_taggingicursunhu9ry INFO:root:Found a tag abinitio-gcs-rw@esa-it-1010.iam.gserviceaccount.com

Default

2021-09-14T17:54:32.979Z

keybank_gcp_taggingicursunhu9ry INFO:root:Checking object [{'Name': 'esa-dev-abinitio-blue-701f', 'Tags': ['dev', 'esa', 'esa-dev-4565', 'esa-dev-abinitio', 'abinitio-gcs-rw@esa-dev-4565.iam.gserviceaccount.com'], 'IP': '10.252.68.47', 'ServiceAccount': 'abinitio-gcs-rw@esa-dev-4565.iam.gserviceaccount.com', 'UnifiedTags': None}]

Default

2021-09-14T17:54:32.979Z

keybank_gcp_taggingicursunhu9ry INFO:root:Found a tag dev

Default

2021-09-14T17:54:32.979Z

keybank_gcp_taggingicursunhu9ry INFO:root:Found a tag esa

Default

2021-09-14T17:54:32.979Z

keybank_gcp_taggingicursunhu9ry INFO:root:Found a tag esa-dev-4565

Default

2021-09-14T17:54:32.979Z

keybank_gcp_taggingicursunhu9ry INFO:root:Found a tag esa-dev-abinitio

Default

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:Found a tag abinitio-gcs-rw@esa-dev-4565.iam.gserviceaccount.com

Default

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:The tags list is: ['https-server', '1092034061644-compute@developer.gserviceaccount.com', 'deeplearning-vm', 'notebook-instance', 'hub-service-account@taw-icadmin-prod-4594.iam.gserviceaccount.com', 'clown-rodeo', 'ssg', 'vmseries', '272257105913-compute@developer.gserviceaccount.com', 'hub-service-account@taw-sscons-prod-7459.iam.gserviceaccount.com', 'hub-service-account@taw-sscomm-prod-6555.iam.gserviceaccount.com', 'gke-us-central1-aqn-composer-378d12e3-gke-e9400bfa-node', 'hub-service-account@taw-aqn-np-7582.iam.gserviceaccount.com', '850290583166-compute@developer.gserviceaccount.com', 'gke-us-central1-composer-test-3c75a4a2-gke-da1ecebc-node', 'hub-service-account@taw-aqn-prod-6903.iam.gserviceaccount.com', '182817735979-compute@developer.gserviceaccount.com', 'gke-elk-di-it-gke', 'gke-elk-di-it-gke-15b1686d-node', 'gke-elk-di-it-gke-elk-di-it-node-pool', '655766297459-compute@developer.gserviceaccount.com', 'gke-cub-caip-prod-gke', 'gke-cub-caip-prod-gke-53663d5f-node', 'gke-cub-caip-prod-gke-cub-caip-prod-node-pool', '849626722198-compute@developer.gserviceaccount.com', 'gke-cub-caip-qv-gke', 'gke-cub-caip-qv-gke-0fc29815-node', 'gke-cub-caip-qv-gke-cub-caip-qv-node-pool', '357713636078-compute@developer.gserviceaccount.com', 'gke-cub-caip-dev2-gke-2e9d9e86-node', 'sa-proj-build@cub-caip-dev-6163.iam.gserviceaccount.com', 'hub-service-account@taw-mktganalytics-prod-8862.iam.gserviceaccount.com', '676420043683-compute@developer.gserviceaccount.com', '580870143374-compute@developer.gserviceaccount.com', 'allow-health-check', 'allow-iap-traffic', 'allow-ssh', 'gke-lr-plos-resque-prod-cluster-67453e38-node', 'load-balanced-backend', 'lrp-sso-iap-ssh', 'prod-service-account@lrp-plos-prod-8014.iam.gserviceaccount.com', 'gke-lr-jarvis-resque-prod-cluster-c1be5819-node', 'prod-service-account@lrp-jarvis-prod-9758.iam.gserviceaccount.com', 'http-server', '319157414516-compute@developer.gserviceaccount.com', 'gke-lr-sso-resque-prod-cluster-3d8d79cc-node', 'prod-service-account@lrp-sso-prod-5413.iam.gserviceaccount.com', '14151480946-compute@developer.gserviceaccount.com', 'gke-lr-jarvis-resque-pp-cluster-3f204e37-node', 'lr-jarvis-pp-service-account@lrp-jarvis-pp-4898.iam.gserviceaccount.com', 'gke-lr-sso-resque-pp-cluster-1ca0b202-node', 'lr-sso-pp-service-account@lrp-sso-pp-9522.iam.gserviceaccount.com', 'gke-lr-plos-resque-bulk-pp-cluster-cc8751a5-node', 'lr-plos-pp-service-account@lrp-plos-pp-9675.iam.gserviceaccount.com', 'allow-prisma-traffic', 'gcpc1lrmtnqa01x', '252070338583-compute@developer.gserviceaccount.com', 'hub-service-account@taw-riskmodeling-prod-5207.iam.gserviceaccount.com', '371023211721-compute@developer.gserviceaccount.com', 'hub-service-account@taw-entpayments-prod-2935.iam.gserviceaccount.com', 'gke-us-central1-composer-test-33f6e4f0-gke-269da35c-node', '681778440407-compute@developer.gserviceaccount.com', '300793833263-compute@developer.gserviceaccount.com', '369895937840-compute@developer.gserviceaccount.com', 'dataproc-notebook-vm', '555878304329-compute@developer.gserviceaccount.com', 'teamcity-server', '270282514584-compute@developer.gserviceaccount.com', 'gke-lr-plos-resque-bulk-dev-cluster-a21e08f3-node', 'lr-plos-dev-service-account@lrp-plos-np-8908.iam.gserviceaccount.com', 'gke-lr-sso-resque-scheduler-dev-cluster-83a88f5f-node', 'lr-sso-dev-service-account@lrp-sso-np-9061.iam.gserviceaccount.com', 'gke-lr-jarvis-resque-dev-cluster-5db8b756-node', 'lr-jarvis-dev-service-account@lrp-jarvis-np-1483.iam.gserviceaccount.com', 'gcpc1lrmtnda01x', '1019852285174-compute@developer.gserviceaccount.com', 'encompass-rdp', '484276021456-compute@developer.gserviceaccount.com', 'gke-cub-qv-cluster', 'gke-cub-qv-cluster-c14f1760-node', 'gke-cub-qv-cluster-default-node-pool', 'tf-gke-cub-qv-cluster-97q4@cub-qv-4058.iam.gserviceaccount.com', 'gke-cub-prod-cluster', 'gke-cub-prod-cluster-default-node-pool', 'gke-cub-prod-cluster-e9dade74-node', 'tf-gke-cub-prod-cluste-40kk@cub-prod-7041.iam.gserviceaccount.com', 'gke-cub-dev-cluster', 'gke-cub-dev-cluster-65b64d47-node', 'gke-cub-dev-cluster-default-node-pool', 'tf-gke-cub-dev-cluster-250v@cub-dev-9459.iam.gserviceaccount.com', 'f5apm-dmz', '141756323161-compute@developer.gserviceaccount.com', '357481354109-compute@developer.gserviceaccount.com', '32295746460-compute@developer.gserviceaccount.com', '237406963935-compute@developer.gserviceaccount.com', '216445914466-compute@developer.gserviceaccount.com', 'dgz', '46363663919-compute@developer.gserviceaccount.com', '473856226375-compute@developer.gserviceaccount.com', '409978152656-compute@developer.gserviceaccount.com', 'hub-service-account@taw-kefstratsvcs-np-7733.iam.gserviceaccount.com', '579412164815-compute@developer.gserviceaccount.com', '168873131038-compute@developer.gserviceaccount.com', '1061682581308-compute@developer.gserviceaccount.com', 'hub-service-account@taw-biccanalytics-prod-5591.iam.gserviceaccount.com', '473366726288-compute@developer.gserviceaccount.com', '390267085193-compute@developer.gserviceaccount.com', 'hub-service-account@taw-sandbox-prod-8405.iam.gserviceaccount.com', 'unifi-prod', '515390751655-compute@developer.gserviceaccount.com', 'hub-service-account@taw-cianalytics-prod-9423.iam.gserviceaccount.com', '279834780111-compute@developer.gserviceaccount.com', '507139751698-compute@developer.gserviceaccount.com', 'hub-service-account@taw-fraudops-np-7929.iam.gserviceaccount.com', '719121789532-compute@developer.gserviceaccount.com', 'unifi-qv', '101377422432-compute@developer.gserviceaccount.com', 'esa', 'esa-prod-7486', 'esa-prod-abinitio', 'prod', 'abinitio-gcs-rw@esa-prod-7486.iam.gserviceaccount.com', 'esa-qv-9135', 'esa-qv-abinitio', 'qv', 'abinitio-gcs-rw@esa-qv-9135.iam.gserviceaccount.com', 'esa-it-1010', 'esa-it-abinitio', 'it', 'abinitio-gcs-rw@esa-it-1010.iam.gserviceaccount.com', 'dev', 'esa-dev-4565', 'esa-dev-abinitio', 'abinitio-gcs-rw@esa-dev-4565.iam.gserviceaccount.com']

INFO:root:The tags list is: ['https-server', '1092034061644-compute@developer.gserviceaccount.com', 'deeplearning-vm', 'notebook-instance', 'hub-service-account@taw-icadmin-prod-4594.iam.gserviceaccount.com', 'clown-rodeo', 'ssg', 'vmseries', '272257105913-compute@developer.gserviceaccount.com', 'hub-service-account@taw-sscons-prod-7459.iam.gserviceaccount.com', 'hub-service-account@taw-sscomm-prod-6555.iam.gserviceaccount.com', 'gke-us-central1-aqn-composer-378d12e3-gke-e9400bfa-node', 'hub-service-account@taw-aqn-np-7582.iam.gserviceaccount.com', '850290583166-compute@developer.gserviceaccount.com', 'gke-us-central1-composer-test-3c75a4a2-gke-da1ecebc-node', 'hub-service-account@taw-aqn-prod-6903.iam.gserviceaccount.com', '182817735979-compute@developer.gserviceaccount.com', 'gke-elk-di-it-gke', 'gke-elk-di-it-gke-15b1686d-node', 'gke-elk-di-it-gke-elk-di-it-node-pool', '655766297459-compute@developer.gserviceaccount.com', 'gke-cub-caip-prod-gke', 'gke-cub-caip-prod-gke-53663d5f-node', 'gke-cub-caip-prod-gke-cub-caip-prod-node-pool', '849626722198-compute@developer.gserviceaccount.com', 'gke-cub-caip-qv-gke', 'gke-cub-caip-qv-gke-0fc29815-node', 'gke-cub-caip-qv-gke-cub-caip-qv-node-pool', '357713636078-compute@developer.gserviceaccount.com', 'gke-cub-caip-dev2-gke-2e9d9e86-node', 'sa-proj-build@cub-caip-dev-6163.iam.gserviceaccount.com', 'hub-service-account@taw-mktganalytics-prod-8862.iam.gserviceaccount.com', '676420043683-compute@developer.gserviceaccount.com', '580870143374-compute@developer.gserviceaccount.com', 'allow-health-check', 'allow-iap-traffic', 'allow-ssh', 'gke-lr-plos-resque-prod-cluster-67453e38-node', 'load-balanced-backend', 'lrp-sso-iap-ssh', 'prod-service-account@lrp-plos-prod-8014.iam.gserviceaccount.com', 'gke-lr-jarvis-resque-prod-cluster-c1be5819-node', 'prod-service-account@lrp-jarvis-prod-9758.iam.gserviceaccount.com', 'http-server', '319157414516-compute@developer.gserviceaccount.com', 'gke-lr-sso-resque-prod-cluster-3d8d79cc-node', 'prod-service-account@lrp-sso-prod-5413.iam.gserviceaccount.com', '14151480946-compute@developer.gserviceaccount.com', 'gke-lr-jarvis-resque-pp-cluster-3f204e37-node', 'lr-jarvis-pp-service-account@lrp-jarvis-pp-4898.iam.gserviceaccount.com', 'gke-lr-sso-resque-pp-cluster-1ca0b202-node', 'lr-sso-pp-service-account@lrp-sso-pp-9522.iam.gserviceaccount.com', 'gke-lr-plos-resque-bulk-pp-cluster-cc8751a5-node', 'lr-plos-pp-service-account@lrp-plos-pp-9675.iam.gserviceaccount.com', 'allow-prisma-traffic', 'gcpc1lrmtnqa01x', '252070338583-compute@developer.gserviceaccount.com', 'hub-service-account@taw-riskmodeling-prod-5207.iam.gserviceaccount.com', '371023211721-compute@developer.gserviceaccount.com', 'hub-service-account@taw-entpayments-prod-2935.iam.gserviceaccount.com', 'gke-us-central1-composer-test-33f6e4f0-gke-269da35c-node', '681778440407-compute@developer.gserviceaccount.com', '300793833263-compute@developer.gserviceaccount.com', '369895937840-compute@developer.gserviceaccount.com', 'dataproc-notebook-vm', '555878304329-compute@developer.gserviceaccount.com', 'teamcity-server', '270282514584-compute@developer.gserviceaccount.com', 'gke-lr-plos-resque-bulk-dev-cluster-a21e08f3-node', 'lr-plos-dev-service-account@lrp-plos-np-8908.iam.gserviceaccount.com', 'gke-lr-sso-resque-scheduler-dev-cluster-83a88f5f-node', 'lr-sso-dev-service-account@lrp-sso-np-9061.iam.gserviceaccount.com', 'gke-lr-jarvis-resque-dev-cluster-5db8b756-node', 'lr-jarvis-dev-service-account@lrp-jarvis-np-1483.iam.gserviceaccount.com', 'gcpc1lrmtnda01x', '1019852285174-compute@developer.gserviceaccount.com', 'encompass-rdp', '484276021456-compute@developer.gserviceaccount.com', 'gke-cub-qv-cluster', 'gke-cub-qv-cluster-c14f1760-node', 'gke-cub-qv-cluster-default-node-pool', 'tf-gke-cub-qv-cluster-97q4@cub-qv-4058.iam.gserviceaccount.com', 'gke-cub-prod-cluster', 'gke-cub-prod-cluster-default-node-pool', 'gke-cub-prod-cluster-e9dade74-node', 'tf-gke-cub-prod-cluste-40kk@cub-prod-7041.iam.gserviceaccount.com', 'gke-cub-dev-cluster', 'gke-cub-dev-cluster-65b64d47-node', 'gke-cub-dev-cluster-default-node-pool', 'tf-gke-cub-dev-cluster-250v@cub-dev-9459.iam.gserviceaccount.com', 'f5apm-dmz', '141756323161-compute@developer.gserviceaccount.com', '357481354109-compute@developer.gserviceaccount.com', '32295746460-compute@developer.gserviceaccount.com', '237406963935-compute@developer.gserviceaccount.com', '216445914466-compute@developer.gserviceaccount.com', 'dgz', '46363663919-compute@developer.gserviceaccount.com', '473856226375-compute@developer.gserviceaccount.com', '409978152656-compute@developer.gserviceaccount.com', 'hub-service-account@taw-kefstratsvcs-np-7733.iam.gserviceaccount.com', '579412164815-compute@developer.gserviceaccount.com', '168873131038-compute@developer.gserviceaccount.com', '1061682581308-compute@developer.gserviceaccount.com', 'hub-service-account@taw-biccanalytics-prod-5591.iam.gserviceaccount.com', '473366726288-compute@developer.gserviceaccount.com', '390267085193-compute@developer.gserviceaccount.com', 'hub-service-account@taw-sandbox-prod-8405.iam.gserviceaccount.com', 'unifi-prod', '515390751655-compute@developer.gserviceaccount.com', 'hub-service-account@taw-cianalytics-prod-9423.iam.gserviceaccount.com', '279834780111-compute@developer.gserviceaccount.com', '507139751698-compute@developer.gserviceaccount.com', 'hub-service-account@taw-fraudops-np-7929.iam.gserviceaccount.com', '719121789532-compute@developer.gserviceaccount.com', 'unifi-qv', '101377422432-compute@developer.gserviceaccount.com', 'esa', 'esa-prod-7486', 'esa-prod-abinitio', 'prod', 'abinitio-gcs-rw@esa-prod-7486.iam.gserviceaccount.com', 'esa-qv-9135', 'esa-qv-abinitio', 'qv', 'abinitio-gcs-rw@esa-qv-9135.iam.gserviceaccount.com', 'esa-it-1010', 'esa-it-abinitio', 'it', 'abinitio-gcs-rw@esa-it-1010.iam.gserviceaccount.com', 'dev', 'esa-dev-4565', 'esa-dev-abinitio', 'abinitio-gcs-rw@esa-dev-4565.iam.gserviceaccount.com']

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:Removed duplicated tags from the Virtual Machines.

Default

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:Adding tags to Panorama and VM-Series.

INFO:root:Adding tags to Panorama and VM-Series.

Default

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:Starting panorama_register_tag_object()

Default

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:SUCCESS: panorama_register_tag()

Default

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:Starting panorama_register_tag_object()

Default

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:SUCCESS: panorama_register_tag()

Default

2021-09-14T17:54:32.980Z

keybank_gcp_taggingicursunhu9ry INFO:root:Starting panorama_register_tag_object()

Default

2021-09-14T17:54:32.981Z

keybank_gcp_taggingicursunhu9ry INFO:root:SUCCESS: panorama_register_tag()

Default

2021-09-14T17:54:32.981Z

keybank_gcp_taggingicursunhu9ry INFO:root:Starting panorama_register_tag_object()
```
