### ISSUE TITLE
 tag 'hub-service-account@taw-modelriskmgmt-prod-1438.iam.gserviceaccount.com' is not a valid reference

### ISSUE THREAD

**Issue by devsecfranklin** [devsecfranklin/pso-gcp-keybank-542851#139]
Could this be exceeding character limit? 

```
Default

2021-09-14T18:34:32.996Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Starting panorama_register_address_object()

Default

2021-09-14T18:34:32.996Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:SUCCESS: panorama_register_address_object()

Default

2021-09-14T18:34:32.996Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Blob: [{'Name': 'sachin-notebook', 'Tags': ['deeplearning-vm', 'notebook-instance', '473366726288-compute@developer.gserviceaccount.com'], 'IP': '10.252.84.39', 'ServiceAccount': '473366726288-compute@developer.gserviceaccount.com', 'UnifiedTags': None}]

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Object: {'Name': 'sachin-notebook', 'Tags': ['deeplearning-vm', 'notebook-instance', '473366726288-compute@developer.gserviceaccount.com'], 'IP': '10.252.84.39', 'ServiceAccount': '473366726288-compute@developer.gserviceaccount.com', 'UnifiedTags': None}

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Attempt to register address object sachin-notebook

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Starting panorama_register_address_object()

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:SUCCESS: panorama_register_address_object()

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Blob: [{'Name': 'python-bcm', 'Tags': ['deeplearning-vm', 'notebook-instance', '390267085193-compute@developer.gserviceaccount.com'], 'IP': '10.252.84.23', 'ServiceAccount': '390267085193-compute@developer.gserviceaccount.com', 'UnifiedTags': None}, {'Name': 'python-mb-vm', 'Tags': ['deeplearning-vm', 'notebook-instance', '390267085193-compute@developer.gserviceaccount.com'], 'IP': '10.252.84.15', 'ServiceAccount': '390267085193-compute@developer.gserviceaccount.com', 'UnifiedTags': None}, {'Name': 'taw-sandbox-np-4895-dataproc-hub-2', 'Tags': ['deeplearning-vm', 'hub-service-account@taw-sandbox-np-4895.iam.gserviceaccount.com'], 'IP': '10.252.84.24', 'ServiceAccount': 'hub-service-account@taw-sandbox-np-4895.iam.gserviceaccount.com', 'UnifiedTags': None}, {'Name': 'gke-us-central1-composer-default-pool-a33d7bbb-dbdu', 'Tags': ['gke-us-central1-composer-test-7f2739fe-gke-0e3d2434-node', 'hub-service-account@taw-sandbox-np-4895.iam.gserviceaccount.com'], 'IP': '192.168.0.10', 'ServiceAccount': 'hub-service-account@taw-sandbox-np-4895.iam.gserviceaccount.com', 'UnifiedTags': None}, {'Name': 'gke-us-central1-composer-default-pool-a33d7bbb-felm', 'Tags': ['gke-us-central1-composer-test-7f2739fe-gke-0e3d2434-node', 'hub-service-account@taw-sandbox-np-4895.iam.gserviceaccount.com'], 'IP': '192.168.0.9', 'ServiceAccount': 'hub-service-account@taw-sandbox-np-4895.iam.gserviceaccount.com', 'UnifiedTags': None}, {'Name': 'gke-us-central1-composer-default-pool-a33d7bbb-x253', 'Tags': ['gke-us-central1-composer-test-7f2739fe-gke-0e3d2434-node', 'hub-service-account@taw-sandbox-np-4895.iam.gserviceaccount.com'], 'IP': '192.168.0.8', 'ServiceAccount': 'hub-service-account@taw-sandbox-np-4895.iam.gserviceaccount.com', 'UnifiedTags': None}]

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Object: {'Name': 'python-bcm', 'Tags': ['deeplearning-vm', 'notebook-instance', '390267085193-compute@developer.gserviceaccount.com'], 'IP': '10.252.84.23', 'ServiceAccount': '390267085193-compute@developer.gserviceaccount.com', 'UnifiedTags': None}

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Attempt to register address object python-bcm

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Starting panorama_register_address_object()

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:SUCCESS: panorama_register_address_object()

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Object: {'Name': 'python-mb-vm', 'Tags': ['deeplearning-vm', 'notebook-instance', '390267085193-compute@developer.gserviceaccount.com'], 'IP': '10.252.84.15', 'ServiceAccount': '390267085193-compute@developer.gserviceaccount.com', 'UnifiedTags': None}

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Attempt to register address object python-mb-vm

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Starting panorama_register_address_object()

Default

2021-09-14T18:34:32.997Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:SUCCESS: panorama_register_address_object()

 

 

Default

2021-09-14T18:34:33.017Z

keybank_gcp_taggingj4c3tcn4npec INFO:root:Starting panorama_register_address_object()

INFO:root:Starting panorama_register_address_object()

Default

2021-09-14T18:34:33.850Z

keybank_gcp_taggingj4c3tcn4npec ERROR:main:Exception on / [POST]

ERROR:main:Exception on / [POST]

Error

2021-09-14T18:34:33.851Z

keybank_gcp_taggingj4c3tcn4npec Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/panos/base.py", line 3661, in method super_method(self, *args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/pan/xapi.py", line 741, in set self.__type_config('set', query, extra_qs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/pan/xapi.py", line 805, in __type_config raise PanXapiError(self.status_detail) pan.xapi.PanXapiError: vsys1 -> address -> python-20210526-161438 -> tag 'hub-service-account@taw-modelriskmgmt-prod-1438.iam.gserviceaccount.com' is not a valid reference

Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/panos/base.py", line 3661, in method super_method(self, *args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/pan/xapi.py", line 741, in set self.__type_config('set', query, extra_qs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/pan/xapi.py", line 805, in __type_config raise PanXapiError(self.status_detail) pan.xapi.PanXapiError: vsys1 -> address -> python-20210526-161438 -> tag 'hub-service-account@taw-modelriskmgmt-prod-1438.iam.gserviceaccount.com' is not a valid reference

Default

2021-09-14T18:34:33.851Z

keybank_gcp_taggingj4c3tcn4npec vsys1 -> address -> python-20210526-161438 -> tag is invalid

vsys1 -> address -> python-20210526-161438 -> tag is invalid

Default

2021-09-14T18:34:33.851Z

keybank_gcp_taggingj4c3tcn4npec vsys1 -> address -> python-20210526-161438 -> tag is invalid

vsys1 -> address -> python-20210526-161438 -> tag is invalid

Default

2021-09-14T18:34:33.851Z

keybank_gcp_taggingj4c3tcn4npec During handling of the above exception, another exception occurred:

Error

2021-09-14T18:34:33.851Z

keybank_gcp_taggingj4c3tcn4npec Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 231, in main register_address_objects(my_firewall, vm_data) File "/workspace/main.py", line 171, in register_address_objects firewall_ao_update[0].create_similar() # Bulk update address objects on VM-Series File "/layers/google.python.pip/pip/lib/python3.8/site-packages/panos/base.py", line 1872, in create_similar dev.xapi.set( File "/layers/google.python.pip/pip/lib/python3.8/site-packages/panos/base.py", line 3682, in method raise the_exception panos.errors.PanDeviceXapiError: vsys1 -> address -> python-20210526-161438 -> tag 'hub-service-account@taw-modelriskmgmt-prod-1438.iam.gserviceaccount.com' is not a valid reference

Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 152, in view_func function(data, context) File "/workspace/main.py", line 231, in main register_address_objects(my_firewall, vm_data) File "/workspace/main.py", line 171, in register_address_objects firewall_ao_update[0].create_similar() # Bulk update address objects on VM-Series File "/layers/google.python.pip/pip/lib/python3.8/site-packages/panos/base.py", line 1872, in create_similar dev.xapi.set( File "/layers/google.python.pip/pip/lib/python3.8/site-packages/panos/base.py", line 3682, in method raise the_exception panos.errors.PanDeviceXapiError: vsys1 -> address -> python-20210526-161438 -> tag 'hub-service-account@taw-modelriskmgmt-prod-1438.iam.gserviceaccount.com' is not a valid reference
```

**Comment by devsecfranklin** [comment]
Looks like we need a check for tag length:

```
 in method raise the_exception panos.errors.PanDeviceXapiError: 
vsys1 -> address -> python-20210526-161438 -> tag 
'hub-service-account@taw-modelriskmgmt-prod-1438.iam.gserviceaccount.com' is not a valid reference
```
